# Mako template for Alembic migration scripts
"""initial_schema

Revision ID: 6b503e01b485
Revises: 
Create Date: 2026-04-22 21:11:16.462128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b503e01b485'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_payment_methods',
    sa.Column('gym_place_id', sa.UUID(), nullable=False),
    sa.Column('kakao_pay_link', sa.Text(), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('account_holder', sa.String(length=50), nullable=True),
    sa.Column('visible_methods', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('gym_place_id')
    )
    op.create_table('gym_profiles',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('court_count', sa.Integer(), nullable=False),
    sa.Column('hours', sa.String(length=100), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=False),
    sa.Column('amenities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_table('outdoor_profiles',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('fee_type', sa.String(length=20), nullable=True),
    sa.Column('floor_status', sa.String(length=50), nullable=True),
    sa.Column('light_status', sa.String(length=50), nullable=True),
    sa.Column('rim_status', sa.String(length=50), nullable=True),
    sa.Column('cleanliness', sa.String(length=50), nullable=True),
    sa.Column('crowd_level', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_table('outdoor_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('visited_at', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VISIBLE', 'HIDDEN', name='review_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outdoor_reviews_place_id'), 'outdoor_reviews', ['place_id'], unique=False)
    op.create_index(op.f('ix_outdoor_reviews_status'), 'outdoor_reviews', ['status'], unique=False)
    op.create_table('owner_gyms',
    sa.Column('gym_place_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('gym_place_id')
    )
    op.create_index(op.f('ix_owner_gyms_owner_user_id'), 'owner_gyms', ['owner_user_id'], unique=False)
    op.create_table('payment_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('payer_name', sa.String(length=50), nullable=False),
    sa.Column('proof_enabled', sa.Boolean(), nullable=False),
    sa.Column('proof_asset_id', sa.UUID(), nullable=True),
    sa.Column('proof_file_name', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id')
    )
    op.create_table('place_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('GALLERY', 'THUMBNAIL', 'REVIEW_PHOTO', 'PROOF', name='asset_type'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_assets_place_id'), 'place_assets', ['place_id'], unique=False)
    op.create_table('places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('GYM', 'OUTDOOR', name='place_type'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_places_district'), 'places', ['district'], unique=False)
    op.create_index(op.f('ix_places_is_active'), 'places', ['is_active'], unique=False)
    op.create_index(op.f('ix_places_type'), 'places', ['type'], unique=False)
    op.create_table('reservation_status_timelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_status_timelines_reservation_id'), 'reservation_status_timelines', ['reservation_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_place_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('time_label', sa.String(length=50), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('booker_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.Column('discount_applied', sa.Boolean(), nullable=False),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('final_price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'AWAITING_TRANSFER', 'TRANSFER_SUBMITTED', 'OWNER_VERIFIED', 'CONFIRMED', 'CANCELLED', name='reservation_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_reservation_gym_date_time', 'reservations', ['gym_place_id', 'date', 'start_time'], unique=False)
    op.create_index(op.f('ix_reservations_gym_place_id'), 'reservations', ['gym_place_id'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    op.create_table('review_moderation_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('HIDE', 'RESTORE', 'APPROVE', name='moderation_action'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_moderation_audits_review_id'), 'review_moderation_audits', ['review_id'], unique=False)
    op.create_table('review_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_photos_review_id'), 'review_photos', ['review_id'], unique=False)
    op.create_table('schedule_exception_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_place_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=True),
    sa.Column('date_range_start', sa.Date(), nullable=True),
    sa.Column('date_range_end', sa.Date(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_exception_rules_gym_place_id'), 'schedule_exception_rules', ['gym_place_id'], unique=False)
    op.create_table('schedule_pricing_policies',
    sa.Column('gym_place_id', sa.UUID(), nullable=False),
    sa.Column('base_hourly_price', sa.Integer(), nullable=False),
    sa.Column('weekend_hourly_price', sa.Integer(), nullable=False),
    sa.Column('discount_person_threshold', sa.Integer(), nullable=True),
    sa.Column('discount_rate_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_fixed_amount', sa.Integer(), nullable=True),
    sa.Column('same_day_only', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('gym_place_id')
    )
    op.create_table('schedule_repeat_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_place_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CLASS', 'REGULAR', name='repeat_rule_type'), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('rrule_spec', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_repeat_rules_gym_place_id'), 'schedule_repeat_rules', ['gym_place_id'], unique=False)
    op.create_table('slot_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_place_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('override_status', sa.Enum('AVAILABLE', 'CLASS', 'REGULAR', 'CLOSED', name='slot_status'), nullable=False),
    sa.Column('override_price', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('OWNER_EDIT', 'SYSTEM_GENERATED', name='slot_override_source'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_place_id', 'date', 'start_time', name='uq_slot_override')
    )
    op.create_index(op.f('ix_slot_overrides_gym_place_id'), 'slot_overrides', ['gym_place_id'], unique=False)
    op.create_table('slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_place_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'CLASS', 'REGULAR', 'CLOSED', name='slot_status'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_place_id', 'date', 'start_time', name='uq_slot')
    )
    op.create_index(op.f('ix_slots_gym_place_id'), 'slots', ['gym_place_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'OWNER', 'ADMIN', 'ORGANIZER', 'OPS', name='user_role'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_slots_gym_place_id'), table_name='slots')
    op.drop_table('slots')
    op.drop_index(op.f('ix_slot_overrides_gym_place_id'), table_name='slot_overrides')
    op.drop_table('slot_overrides')
    op.drop_index(op.f('ix_schedule_repeat_rules_gym_place_id'), table_name='schedule_repeat_rules')
    op.drop_table('schedule_repeat_rules')
    op.drop_table('schedule_pricing_policies')
    op.drop_index(op.f('ix_schedule_exception_rules_gym_place_id'), table_name='schedule_exception_rules')
    op.drop_table('schedule_exception_rules')
    op.drop_index(op.f('ix_review_photos_review_id'), table_name='review_photos')
    op.drop_table('review_photos')
    op.drop_index(op.f('ix_review_moderation_audits_review_id'), table_name='review_moderation_audits')
    op.drop_table('review_moderation_audits')
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_gym_place_id'), table_name='reservations')
    op.drop_index('ix_reservation_gym_date_time', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_reservation_status_timelines_reservation_id'), table_name='reservation_status_timelines')
    op.drop_table('reservation_status_timelines')
    op.drop_index(op.f('ix_places_type'), table_name='places')
    op.drop_index(op.f('ix_places_is_active'), table_name='places')
    op.drop_index(op.f('ix_places_district'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_place_assets_place_id'), table_name='place_assets')
    op.drop_table('place_assets')
    op.drop_table('payment_transfers')
    op.drop_index(op.f('ix_owner_gyms_owner_user_id'), table_name='owner_gyms')
    op.drop_table('owner_gyms')
    op.drop_index(op.f('ix_outdoor_reviews_status'), table_name='outdoor_reviews')
    op.drop_index(op.f('ix_outdoor_reviews_place_id'), table_name='outdoor_reviews')
    op.drop_table('outdoor_reviews')
    op.drop_table('outdoor_profiles')
    op.drop_table('gym_profiles')
    op.drop_table('gym_payment_methods')
    # ### end Alembic commands ###
